services:
  - type: web
    name: flash-neiga-backend
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        value: sqlite:///./flash_neiga.db
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/backend
      sizeGB: 1
