services:
  - type: web
    name: flash-neiga-backend
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: flash-neiga-db
          property: connectionString

databases:
  - name: flash-neiga-db
    databaseName: flash_neiga
    user: flash_neiga_user
    plan: free
